/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csv.analyser;

import org.junit.Test;
import static org.junit.Assert.*;

public class AnalyserTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        Analyser classUnderTest = new Analyser();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
