/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csv.analyser;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

public class Analyser {

    private static final int COL_MING_CHENG = 1;
    private static final int COL_CHENG_JIAO_LIANG = 5;

    private static final char NEWLINE = '\n';
    private static final String COMMA = ",";
    private static final File inputFile = new File("input/20211021161135.csv");
    private static final File outputFile = new File("output/20211021161135.csv");

    private final String date;

    public Analyser() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        date = dtf.format(now);
    }

    public static void main(String[] args) throws IOException {
        Scanner scanner = new Scanner(inputFile, StandardCharsets.UTF_8);
        Writer writer = new OutputStreamWriter(new FileOutputStream(outputFile), StandardCharsets.UTF_8);
        Analyser analyser = new Analyser();
        analyser.processFile(scanner, writer);
        writer.close();
    }

    private void processFile(Scanner scanner, Writer writer) throws IOException {
        String processedTitle = processTitle(scanner.nextLine());
        appendLine(processedTitle, writer);

        while (scanner.hasNext()) {
            String processedLine = processLine(scanner.nextLine());
            appendLine(processedLine, writer);
        }
    }

    private String processTitle(String titleRow) {
        String[] titles = titleRow.split(COMMA);
        StringBuilder result = new StringBuilder();
        result.append("收盘日期");

        for (int i = 0; i < titles.length; i++) {
            String title = titles[i];
            if (i != COL_MING_CHENG) {
                if (i == COL_CHENG_JIAO_LIANG) {
                    title = "当日收盘成交量";
                }
                result.append(COMMA).append(title);
            }
        }
        return result.toString();
    }

    private String processLine(String line) {
        StringBuilder builder = new StringBuilder();
        builder.append(date);
        String[] columns = line.split(COMMA);

        for (int i = 0; i < columns.length; i++) {
            String column = columns[i];
            if (i != COL_MING_CHENG) {

            }
        }

        return builder.toString();
    }

    private void appendLine(String line, Writer writer) throws IOException {
        writer.append(line).append(NEWLINE);
    }

    private void print(String s) {
        PrintStream ps = new PrintStream(System.out, true, StandardCharsets.UTF_8);
        ps.println(s);
    }
}
